<html>
<head>
</head>
<body>
  <header>
    <h1>WebhookTriggeredWebAppPipeline</h1>
  </header>
  <section>
    <p>This is a Java Web Application generated by maven archetype "Maven-Archetype-WebApp" using the maven command "mvn archetype:generate" in maven server.</p>
    <p>After building, an artifact "war" is generated and can be deployed to a tomcat server.</p>
  </section>
</body>
</html>
